---
sudo: required
dist: trusty
language: python
python: "2.7"

env:
  - ROLE_OPTIONS="postgresql_version=9.3 postgresql_shared_buffers=32MB"
  - ROLE_OPTIONS="postgresql_version=9.4 postgresql_shared_buffers=32MB"
  - ROLE_OPTIONS="postgresql_version=9.5 postgresql_shared_buffers=32MB"

before_install:
  # Remove the PostgreSQL installed by Travis
  - sudo apt-get purge pgdg-keyring '^postgresql.*' -y
  - sudo apt-get autoremove -y -qq
  - sudo rm -rf /etc/postgresql
  - sudo rm -rf /var/lib/postgresql
  - sudo rm -f /etc/apt/sources.list.d/pgdg-source.list
  # Install some dependencies
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y python-apt python-pycurl locales
  - echo 'en_US.UTF-8 UTF-8' | sudo tee /var/lib/locales/supported.d/local

install:
  - pip install ansible
  - ansible --version

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Syntax check
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Play test
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local -e "$ROLE_OPTIONS"

  # Idempotence test
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local -e "$ROLE_OPTIONS"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
